#!/usr/bin/env python3
"""End-to-end tests for update_readme.py.

Runs the real script as a subprocess against a throwaway repo layout in a
temp directory (never touches the real Photos/ or README.md), and checks the
generated output, --check validation, and idempotency.

Usage:
    scripts/test_update_readme.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "update_readme.py"

# Fake JPEG bytes -- just needs a .jpg extension for the script to pick it
# up. It has no real EXIF DateTimeOriginal, so exiftool/exiv2 (if installed)
# find nothing and the script falls back to file mtime. That keeps ordering
# fully controlled by tests via os.utime(), independent of what EXIF tooling
# happens to be installed on the machine running the tests.
FAKE_JPEG_BYTES = b"\xff\xd8\xff\xe0not a real jpeg, just needs the right extension\xff\xd9"

START_MARKER = "<!-- PHOTOS:START (auto-generated by scripts/update_readme.py -- do not edit by hand) -->"
END_MARKER = "<!-- PHOTOS:END -->"


class UpdateReadmeE2ETest(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="update_readme_test_"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

        # Mirror the real repo layout: scripts/ + Photos/ + README.md,
        # sitting next to the real scripts/ dir so `scripts/update_readme.py`
        # resolves repo_root as this temp dir (repo_root = script's parent.parent).
        self.repo = self.tmp
        self.scripts_dir = self.repo / "scripts"
        self.scripts_dir.mkdir()
        shutil.copy(SCRIPT, self.scripts_dir / "update_readme.py")
        self.local_script = self.scripts_dir / "update_readme.py"

        self.photos_dir = self.repo / "Photos"
        self.photos_dir.mkdir()

        self.readme = self.repo / "README.md"

    def write_readme(self, body_before="# Test Repo\nSome intro text.\n\n"):
        self.readme.write_text(body_before + START_MARKER + "\n" + END_MARKER + "\n")

    def add_photo(self, name: str, mtime_epoch: float) -> Path:
        path = self.photos_dir / name
        path.write_bytes(FAKE_JPEG_BYTES)
        os.utime(path, (mtime_epoch, mtime_epoch))
        return path

    def run_script(self, *extra_args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, str(self.local_script), *extra_args],
            capture_output=True, text=True, cwd=self.repo,
        )

    # -- tests --------------------------------------------------------

    def test_fresh_run_orders_newest_first_and_groups_by_date(self):
        self.write_readme()
        # Two photos on day 2, one on day 1 (day 2 is newer).
        self.add_photo("a_older_on_day2.jpg", 1_700_000_000)
        self.add_photo("b_newer_on_day2.jpg", 1_700_003_600)
        self.add_photo("c_day1.jpg", 1_699_900_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)

        text = self.readme.read_text()
        self.assertIn("# Test Repo\nSome intro text.", text, "content outside markers must survive")
        self.assertIn(START_MARKER, text)
        self.assertIn(END_MARKER, text)

        # Newer photo on day 2 must appear before the older one on day 2,
        # and the whole day-2 group must appear before day-1.
        pos_b = text.index("b_newer_on_day2.jpg")
        pos_a = text.index("a_older_on_day2.jpg")
        pos_c = text.index("c_day1.jpg")
        self.assertLess(pos_b, pos_a, "newer photo within the same day must come first")
        self.assertLess(pos_a, pos_c, "newer day's group must come before older day's group")

    def test_check_fails_on_untouched_readme(self):
        self.write_readme()
        self.add_photo("only.jpg", 1_700_000_000)

        result = self.run_script("--check")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("stale", result.stderr.lower())

    def test_check_passes_after_generation(self):
        self.write_readme()
        self.add_photo("only.jpg", 1_700_000_000)

        gen = self.run_script()
        self.assertEqual(gen.returncode, 0, gen.stderr)

        check = self.run_script("--check")
        self.assertEqual(check.returncode, 0, check.stderr)
        self.assertIn("OK", check.stdout)

    def test_idempotent_on_repeated_runs(self):
        self.write_readme()
        for i, epoch in enumerate([1_700_000_000, 1_700_050_000, 1_699_000_000]):
            self.add_photo(f"photo{i}.jpg", epoch)

        self.run_script()
        first_pass = self.readme.read_text()
        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        second_pass = self.readme.read_text()
        self.assertEqual(first_pass, second_pass)

    def test_detects_orphaned_photo_added_after_generation(self):
        self.write_readme()
        self.add_photo("first.jpg", 1_700_000_000)
        self.run_script()

        # Drop a new photo in without regenerating -- workflow violation.
        self.add_photo("second.jpg", 1_700_100_000)

        check = self.run_script("--check")
        self.assertNotEqual(check.returncode, 0)
        self.assertIn("second.jpg", check.stderr)

    def test_detects_dangling_reference_to_deleted_photo(self):
        self.write_readme()
        self.add_photo("keep.jpg", 1_700_000_000)
        gone = self.add_photo("delete_me.jpg", 1_700_100_000)
        self.run_script()

        gone.unlink()

        check = self.run_script("--check")
        self.assertNotEqual(check.returncode, 0)
        self.assertIn("delete_me.jpg", check.stderr)

    def test_fails_cleanly_with_no_photos(self):
        self.write_readme()
        result = self.run_script()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("no images found", result.stderr.lower())

    def test_fails_cleanly_without_markers(self):
        self.readme.write_text("# Test Repo\nNo markers here.\n")
        self.add_photo("only.jpg", 1_700_000_000)
        result = self.run_script()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("marker", result.stderr.lower())

    def test_non_image_files_are_ignored(self):
        self.write_readme()
        self.add_photo("real.jpg", 1_700_000_000)
        (self.photos_dir / "notes.txt").write_text("not a photo")
        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertNotIn("notes.txt", text)

    def test_content_outside_markers_untouched_on_regeneration(self):
        custom_intro = "# My Custom Title\nSome custom words the user wrote.\n\n"
        custom_outro = "\n## Footer\nDon't touch this either.\n"
        self.readme.write_text(custom_intro + START_MARKER + "\n" + END_MARKER + "\n" + custom_outro)
        self.add_photo("only.jpg", 1_700_000_000)

        self.run_script()
        text = self.readme.read_text()
        self.assertIn(custom_intro, text)
        self.assertIn(custom_outro, text)


if __name__ == "__main__":
    unittest.main()
