#!/usr/bin/env python3
"""End-to-end tests for update_readme.py.

Runs the real script as a subprocess against a throwaway repo layout in a
temp directory (never touches the real Photos/ or README.md), and checks the
generated output, --check validation, and idempotency.

Usage:
    scripts/test_update_readme.py
"""
from __future__ import annotations

import os
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
import zlib
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "update_readme.py"

# Fake JPEG bytes -- just needs a .jpg/.jpeg extension for the script to pick
# it up. It has no real EXIF DateTimeOriginal, so exiftool/exiv2 (if
# installed) find nothing and the script falls back to file mtime. That keeps
# ordering fully controlled by tests via os.utime(), independent of what EXIF
# tooling happens to be installed on the machine running the tests, and
# doubles as a check that the tools don't choke on a malformed file.
FAKE_JPEG_BYTES = b"\xff\xd8\xff\xe0not a real jpeg, just needs the right extension\xff\xd9"


def make_minimal_png(width: int = 1, height: int = 1) -> bytes:
    """A genuinely valid, decodable 1x1 (by default) RGB PNG.

    Real screenshot tools (e.g. hyprshot) emit plain PNGs with no EXIF
    DateTimeOriginal chunk, so this -- unlike FAKE_JPEG_BYTES -- is built to
    actually pass as a real image, closer to what the tool sees in practice.
    """
    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data))

    signature = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)  # 8-bit RGB
    raw_scanlines = b"".join(b"\x00" + b"\x00\x00\x00" * width for _ in range(height))
    idat = zlib.compress(raw_scanlines)
    return signature + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


FAKE_PNG_BYTES = make_minimal_png()

# Fake MP4 bytes -- just needs a video extension for the script to pick it up.
# Real camera/screen-recorder clips rarely carry EXIF DateTimeOriginal either
# (confirmed against real .MP4 files: exiv2 finds nothing), so mtime fallback
# is the realistic path here too.
FAKE_MP4_BYTES = b"\x00\x00\x00\x18ftypmp42not a real mp4, just needs the right extension"

START_MARKER = "<!-- PHOTOS:START (auto-generated by scripts/update_readme.py -- do not edit by hand) -->"
END_MARKER = "<!-- PHOTOS:END -->"


class UpdateReadmeE2ETest(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="update_readme_test_"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

        # Mirror the real repo layout: scripts/ + Photos/ + README.md,
        # sitting next to the real scripts/ dir so `scripts/update_readme.py`
        # resolves repo_root as this temp dir (repo_root = script's parent.parent).
        self.repo = self.tmp
        self.scripts_dir = self.repo / "scripts"
        self.scripts_dir.mkdir()
        shutil.copy(SCRIPT, self.scripts_dir / "update_readme.py")
        self.local_script = self.scripts_dir / "update_readme.py"

        self.photos_dir = self.repo / "Photos"
        self.photos_dir.mkdir()

        self.readme = self.repo / "README.md"

    def write_readme(self, body_before="# Test Repo\nSome intro text.\n\n"):
        self.readme.write_text(body_before + START_MARKER + "\n" + END_MARKER + "\n")

    def add_photo(self, name: str, mtime_epoch: float) -> Path:
        path = self.photos_dir / name
        suffix = path.suffix.lower()
        content = FAKE_PNG_BYTES if suffix == ".png" else FAKE_JPEG_BYTES
        path.write_bytes(content)
        os.utime(path, (mtime_epoch, mtime_epoch))
        return path

    def add_video(self, name: str, mtime_epoch: float) -> Path:
        path = self.photos_dir / name
        path.write_bytes(FAKE_MP4_BYTES)
        os.utime(path, (mtime_epoch, mtime_epoch))
        return path

    def run_script(self, *extra_args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, str(self.local_script), *extra_args],
            capture_output=True, text=True, cwd=self.repo,
        )

    # -- tests --------------------------------------------------------

    def test_fresh_run_orders_newest_first_and_groups_by_date(self):
        self.write_readme()
        # Two photos on day 2, one on day 1 (day 2 is newer).
        self.add_photo("a_older_on_day2.jpg", 1_700_000_000)
        self.add_photo("b_newer_on_day2.jpg", 1_700_003_600)
        self.add_photo("c_day1.jpg", 1_699_900_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)

        text = self.readme.read_text()
        self.assertIn("# Test Repo\nSome intro text.", text, "content outside markers must survive")
        self.assertIn(START_MARKER, text)
        self.assertIn(END_MARKER, text)

        # Newer photo on day 2 must appear before the older one on day 2,
        # and the whole day-2 group must appear before day-1.
        pos_b = text.index("b_newer_on_day2.jpg")
        pos_a = text.index("a_older_on_day2.jpg")
        pos_c = text.index("c_day1.jpg")
        self.assertLess(pos_b, pos_a, "newer photo within the same day must come first")
        self.assertLess(pos_a, pos_c, "newer day's group must come before older day's group")

    def test_check_fails_on_untouched_readme(self):
        self.write_readme()
        self.add_photo("only.jpg", 1_700_000_000)

        result = self.run_script("--check")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("stale", result.stderr.lower())

    def test_check_passes_after_generation(self):
        self.write_readme()
        self.add_photo("only.jpg", 1_700_000_000)

        gen = self.run_script()
        self.assertEqual(gen.returncode, 0, gen.stderr)

        check = self.run_script("--check")
        self.assertEqual(check.returncode, 0, check.stderr)
        self.assertIn("OK", check.stdout)

    def test_idempotent_on_repeated_runs(self):
        self.write_readme()
        for i, epoch in enumerate([1_700_000_000, 1_700_050_000, 1_699_000_000]):
            self.add_photo(f"photo{i}.jpg", epoch)

        self.run_script()
        first_pass = self.readme.read_text()
        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        second_pass = self.readme.read_text()
        self.assertEqual(first_pass, second_pass)

    def test_detects_orphaned_photo_added_after_generation(self):
        self.write_readme()
        self.add_photo("first.jpg", 1_700_000_000)
        self.run_script()

        # Drop a new photo in without regenerating -- workflow violation.
        self.add_photo("second.jpg", 1_700_100_000)

        check = self.run_script("--check")
        self.assertNotEqual(check.returncode, 0)
        self.assertIn("second.jpg", check.stderr)

    def test_detects_dangling_reference_to_deleted_photo(self):
        self.write_readme()
        self.add_photo("keep.jpg", 1_700_000_000)
        gone = self.add_photo("delete_me.jpg", 1_700_100_000)
        self.run_script()

        gone.unlink()

        check = self.run_script("--check")
        self.assertNotEqual(check.returncode, 0)
        self.assertIn("delete_me.jpg", check.stderr)

    def test_fails_cleanly_with_no_photos(self):
        self.write_readme()
        result = self.run_script()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("no images or videos found", result.stderr.lower())

    def test_fails_cleanly_without_markers(self):
        self.readme.write_text("# Test Repo\nNo markers here.\n")
        self.add_photo("only.jpg", 1_700_000_000)
        result = self.run_script()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("marker", result.stderr.lower())

    def test_non_image_files_are_ignored(self):
        self.write_readme()
        self.add_photo("real.jpg", 1_700_000_000)
        (self.photos_dir / "notes.txt").write_text("not a photo")
        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertNotIn("notes.txt", text)

    def test_content_outside_markers_untouched_on_regeneration(self):
        custom_intro = "# My Custom Title\nSome custom words the user wrote.\n\n"
        custom_outro = "\n## Footer\nDon't touch this either.\n"
        self.readme.write_text(custom_intro + START_MARKER + "\n" + END_MARKER + "\n" + custom_outro)
        self.add_photo("only.jpg", 1_700_000_000)

        self.run_script()
        text = self.readme.read_text()
        self.assertIn(custom_intro, text)
        self.assertIn(custom_outro, text)

    # -- image format coverage (png / jpeg) ----------------------------

    def test_png_only_is_picked_up_and_validated(self):
        self.write_readme()
        self.add_photo("screenshot.png", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertIn('<img src="Photos/screenshot.png"', text)

        check = self.run_script("--check")
        self.assertEqual(check.returncode, 0, check.stderr)

    def test_png_with_no_exif_falls_back_to_mtime_with_warning(self):
        # Real screenshot tools (hyprshot etc.) write plain PNGs with no
        # DateTimeOriginal, so this exercises the same fallback path real
        # screenshots hit, and checks the user is told about it.
        self.write_readme()
        self.add_photo("screenshot.png", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("no EXIF capture date found", result.stderr)
        self.assertIn("screenshot.png", result.stderr)

    def test_jpeg_extension_variant_supported(self):
        # ".jpeg" as well as ".jpg" -- both are common in the wild.
        self.write_readme()
        self.add_photo("camera.jpeg", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertIn('<img src="Photos/camera.jpeg"', text)

    def test_uppercase_extensions_supported(self):
        # Cameras commonly write .JPG/.PNG in uppercase.
        self.write_readme()
        self.add_photo("camera.JPG", 1_700_000_000)
        self.add_photo("screenshot.PNG", 1_700_100_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertIn('<img src="Photos/camera.JPG"', text)
        self.assertIn('<img src="Photos/screenshot.PNG"', text)

    def test_png_and_jpeg_sorted_together_by_date(self):
        # Mixed formats in the same folder must interleave correctly by
        # capture time, not get grouped/sorted by extension.
        self.write_readme()
        self.add_photo("a_jpeg_newest.jpg", 1_700_100_000)
        self.add_photo("b_png_middle.png", 1_700_050_000)
        self.add_photo("c_jpeg_oldest.jpg", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()

        pos_a = text.index("a_jpeg_newest.jpg")
        pos_b = text.index("b_png_middle.png")
        pos_c = text.index("c_jpeg_oldest.jpg")
        self.assertLess(pos_a, pos_b)
        self.assertLess(pos_b, pos_c)

    def test_check_detects_new_png_dropped_in_after_generation(self):
        self.write_readme()
        self.add_photo("existing.jpg", 1_700_000_000)
        self.run_script()

        self.add_photo("new_screenshot.png", 1_700_100_000)

        check = self.run_script("--check")
        self.assertNotEqual(check.returncode, 0)
        self.assertIn("new_screenshot.png", check.stderr)

    # -- videos ---------------------------------------------------------

    def test_videos_appear_in_own_section_after_photos(self):
        self.write_readme()
        self.add_photo("photo.jpg", 1_700_000_000)
        self.add_video("clip.mp4", 1_700_100_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()

        self.assertIn('<video src="Photos/clip.mp4" width="300" controls></video>', text)
        self.assertIn("## Videos", text)

        # The Videos section must come after the photo date group(s).
        pos_photo_tag = text.index('<img src="Photos/photo.jpg"')
        pos_videos_heading = text.index("## Videos")
        pos_video_tag = text.index("<video")
        self.assertLess(pos_photo_tag, pos_videos_heading)
        self.assertLess(pos_videos_heading, pos_video_tag)

        check = self.run_script("--check")
        self.assertEqual(check.returncode, 0, check.stderr)

    def test_no_videos_section_when_no_videos_present(self):
        self.write_readme()
        self.add_photo("photo.jpg", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertNotIn("## Videos", text)
        self.assertNotIn("<video", text)

    def test_video_with_no_exif_falls_back_to_mtime_with_warning(self):
        self.write_readme()
        self.add_video("clip.mp4", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("no EXIF capture date found", result.stderr)
        self.assertIn("clip.mp4", result.stderr)

    def test_multiple_videos_grouped_by_date_newest_first(self):
        self.write_readme()
        self.add_video("older.mp4", 1_700_000_000)
        self.add_video("newer.mov", 1_700_100_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()

        pos_newer = text.index("newer.mov")
        pos_older = text.index("older.mp4")
        self.assertLess(pos_newer, pos_older, "newer video must come first")

        check = self.run_script("--check")
        self.assertEqual(check.returncode, 0, check.stderr)

    def test_check_detects_new_video_dropped_in_after_generation(self):
        self.write_readme()
        self.add_photo("existing.jpg", 1_700_000_000)
        self.run_script()

        self.add_video("new_clip.mp4", 1_700_100_000)

        check = self.run_script("--check")
        self.assertNotEqual(check.returncode, 0)
        self.assertIn("new_clip.mp4", check.stderr)

    def test_video_only_no_photos(self):
        self.write_readme()
        self.add_video("only.mp4", 1_700_000_000)

        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        text = self.readme.read_text()
        self.assertIn("<video", text)

        check = self.run_script("--check")
        self.assertEqual(check.returncode, 0, check.stderr)

    def test_idempotent_with_photos_and_videos_mixed(self):
        self.write_readme()
        self.add_photo("photo.jpg", 1_700_000_000)
        self.add_video("clip.mp4", 1_700_050_000)

        self.run_script()
        first_pass = self.readme.read_text()
        result = self.run_script()
        self.assertEqual(result.returncode, 0, result.stderr)
        second_pass = self.readme.read_text()
        self.assertEqual(first_pass, second_pass)


if __name__ == "__main__":
    unittest.main()
