#!/usr/bin/env python3
"""Regenerate the photo gallery section of README.md from Photos/.

Workflow: drop images into Photos/, then run this script.

Images are ordered newest-first by capture date (EXIF DateTimeOriginal,
treated as UTC and converted to local time, falling back to file mtime when
no EXIF date is present) and grouped under `## YYYY-MM-DD` headings. The
generated block is written between two markers in README.md; everything
outside the markers is left untouched.

Usage:
    scripts/update_readme.py            # regenerate README.md
    scripts/update_readme.py --check    # validate only, no writes (CI mode)
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

START_MARKER = "<!-- PHOTOS:START (auto-generated by scripts/update_readme.py -- do not edit by hand) -->"
END_MARKER = "<!-- PHOTOS:END -->"

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}

EXIFTOOL = shutil.which("exiftool")
EXIV2 = shutil.which("exiv2")


def detect_local_timezone() -> str:
    """Best-effort IANA timezone name for converting EXIF (UTC) timestamps."""
    try:
        link = os.readlink("/etc/localtime")
        marker = "zoneinfo/"
        idx = link.find(marker)
        if idx != -1:
            return link[idx + len(marker):]
    except OSError:
        pass
    return "UTC"


def read_exif_datetime(path: Path) -> datetime | None:
    """Try to read the original capture time embedded in the image."""
    if EXIFTOOL:
        try:
            out = subprocess.run(
                ["exiftool", "-DateTimeOriginal", "-s3", str(path)],
                capture_output=True, text=True, timeout=10, check=False,
            )
            val = out.stdout.strip()
            if val:
                return datetime.strptime(val, "%Y:%m:%d %H:%M:%S")
        except (OSError, ValueError):
            pass
    if EXIV2:
        try:
            out = subprocess.run(
                ["exiv2", "-g", "Exif.Photo.DateTimeOriginal", "-Pv", str(path)],
                capture_output=True, text=True, timeout=10, check=False,
            )
            val = out.stdout.strip()
            if val:
                return datetime.strptime(val, "%Y:%m:%d %H:%M:%S")
        except (OSError, ValueError):
            pass
    return None


def get_capture_datetime(path: Path, tz: ZoneInfo) -> tuple[datetime, str]:
    dt = read_exif_datetime(path)
    if dt is not None:
        local = dt.replace(tzinfo=timezone.utc).astimezone(tz)
        return local.replace(tzinfo=None), "exif"
    return datetime.fromtimestamp(path.stat().st_mtime), "mtime"


def collect_photos(photos_dir: Path, tz: ZoneInfo) -> list[tuple[datetime, str, Path]]:
    photos = []
    for path in photos_dir.iterdir():
        if path.is_file() and path.suffix.lower() in IMAGE_EXTS:
            dt, source = get_capture_datetime(path, tz)
            photos.append((dt, source, path))
    photos.sort(key=lambda item: item[0], reverse=True)
    return photos


def build_block(photos: list[tuple[datetime, str, Path]], repo_root: Path, width: int) -> str:
    lines: list[str] = []
    current_date = None
    for dt, _source, path in photos:
        date_str = dt.date().isoformat()
        if date_str != current_date:
            if current_date is not None:
                lines.append("")
            lines.append(f"## {date_str}")
            lines.append("")
            current_date = date_str
        rel = path.relative_to(repo_root).as_posix()
        lines.append(f'<img src="{rel}" width="{width}" alt="{path.name}">')
    return "\n".join(lines) + "\n"


def extract_current_block(readme_text: str) -> str | None:
    if START_MARKER not in readme_text or END_MARKER not in readme_text:
        return None
    _, rest = readme_text.split(START_MARKER, 1)
    block, _ = rest.split(END_MARKER, 1)
    return block.strip("\n")


def render_readme(readme_text: str, block: str) -> str:
    if START_MARKER not in readme_text or END_MARKER not in readme_text:
        raise SystemExit(
            "README.md is missing the PHOTOS:START/PHOTOS:END markers.\n"
            f"Add these two lines where the gallery should go:\n{START_MARKER}\n{END_MARKER}"
        )
    pre, rest = readme_text.split(START_MARKER, 1)
    _, post = rest.split(END_MARKER, 1)
    return pre + START_MARKER + "\n\n" + block + "\n" + END_MARKER + post


def validate(repo_root: Path, photos_dir: Path, readme_text: str) -> list[str]:
    errors = []

    on_disk = {p.name for p in photos_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS}
    dir_name = re.escape(photos_dir.name)
    ref_counts = Counter(re.findall(rf'<img src="{dir_name}/([^"]+)"', readme_text))
    referenced = set(ref_counts)

    missing_from_readme = on_disk - referenced
    if missing_from_readme:
        errors.append(f"Photos on disk but not referenced in README: {sorted(missing_from_readme)}")

    dangling = referenced - on_disk
    if dangling:
        errors.append(f"README references images that don't exist on disk: {sorted(dangling)}")

    duplicate_refs = sorted(name for name, count in ref_counts.items() if count > 1)
    if duplicate_refs:
        errors.append(f"Images referenced more than once in README: {duplicate_refs}")

    dates = re.findall(r"^## (\d{4}-\d{2}-\d{2})$", readme_text, re.MULTILINE)
    if dates != sorted(dates, reverse=True):
        errors.append("Date headings in README are not in descending (newest-first) order")
    if len(dates) != len(set(dates)):
        errors.append("Duplicate date headings found in README")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--photos-dir", default="Photos", help="Directory of images, relative to repo root")
    parser.add_argument("--readme", default="README.md", help="README file to update, relative to repo root")
    parser.add_argument("--width", type=int, default=300, help="Display width in px for each image")
    parser.add_argument(
        "--timezone", default=None,
        help="IANA timezone to convert EXIF (UTC) timestamps into, e.g. Australia/Sydney. "
             "Defaults to the system's local timezone.",
    )
    parser.add_argument("--check", action="store_true", help="Validate only; don't write, exit non-zero if stale/invalid")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    photos_dir = repo_root / args.photos_dir
    readme_path = repo_root / args.readme
    tz_name = args.timezone or detect_local_timezone()
    try:
        tz = ZoneInfo(tz_name)
    except Exception:
        print(f"FAIL: unknown timezone {tz_name!r}", file=sys.stderr)
        return 1

    if not photos_dir.is_dir():
        print(f"FAIL: photos directory not found: {photos_dir}", file=sys.stderr)
        return 1
    if not readme_path.is_file():
        print(f"FAIL: README not found: {readme_path}", file=sys.stderr)
        return 1

    photos = collect_photos(photos_dir, tz)
    if not photos:
        print(f"FAIL: no images found in {photos_dir}", file=sys.stderr)
        return 1

    mtime_fallback = [p.name for _dt, source, p in photos if source == "mtime"]
    if mtime_fallback:
        print(
            f"WARNING: no EXIF capture date found for {len(mtime_fallback)} file(s); "
            f"using file modification time instead: {sorted(mtime_fallback)}",
            file=sys.stderr,
        )

    block = build_block(photos, repo_root, args.width)
    readme_text = readme_path.read_text()

    if args.check:
        errors = validate(repo_root, photos_dir, readme_text)
        current_block = extract_current_block(readme_text)
        if current_block is None:
            errors.append("README.md is missing the PHOTOS:START/PHOTOS:END markers")
        elif current_block != block.strip("\n"):
            errors.append("README photo gallery is stale; run scripts/update_readme.py to regenerate")
        if errors:
            for e in errors:
                print(f"FAIL: {e}", file=sys.stderr)
            return 1
        print(f"OK: README.md is up to date with {len(photos)} photo(s) in {photos_dir.name}/")
        return 0

    new_text = render_readme(readme_text, block)
    readme_path.write_text(new_text)

    errors = validate(repo_root, photos_dir, new_text)
    if errors:
        for e in errors:
            print(f"FAIL: {e}", file=sys.stderr)
        return 1

    n_dates = len({dt.date() for dt, _s, _p in photos})
    print(f"Updated {readme_path.relative_to(repo_root)}: {len(photos)} photo(s) across {n_dates} date(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
